apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-challenge-users-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/sqlserver
