networks:
  techChallengeNetwork:
    external: true

services:
  tech-challenge-contacts-command-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S3cur3P@ssW0rd
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    restart: always
    networks:
      - techChallengeNetwork
