volumes:
  sqlserver_data:
  grafana-data:

networks:
  techChallengeNetwork:
    external: true

services:
  contacts_command_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S3cur3P@ssW0rd
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    networks:
      - techChallengeNetwork

  contacts_command_sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      contacts_command_sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S contacts_command_sqlserver -U sa -P S3cur3P@ssW0rd -d master -i docker-entrypoint-initdb.d/init.sql -C;
      echo "All done!";
      '
    networks:
      - techChallengeNetwork
