// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosTech.TechChallenge.Contacts.Command.Infra.Context;

#nullable disable

namespace PosTech.TechChallenge.Contacts.Command.Infra.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20240830183611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosTech.TechChallenge.Contacts.Command.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DDD")
                        .HasMaxLength(2)
                        .HasColumnType("TINYINT")
                        .HasColumnName("DDD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR(9)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("58f110af-9e0c-4f22-a7e4-9974c1dbb83d"),
                            DDD = (byte)43,
                            Email = "pedro-ferreira85@yahoo.com.br",
                            Name = "Pedro Henrique Erick Ferreira",
                            PhoneNumber = "989340101"
                        },
                        new
                        {
                            Id = new Guid("60d6e410-f0b0-4dde-a1bc-3a7a8175a8e6"),
                            DDD = (byte)63,
                            Email = "thomas.pires@credendio.com.br",
                            Name = "Thomas Vinicius João Pires",
                            PhoneNumber = "989769978"
                        },
                        new
                        {
                            Id = new Guid("c4006681-aba6-4738-9507-041788b7d55f"),
                            DDD = (byte)11,
                            Email = "julia92@casabellavidros.com.br",
                            Name = "Julia Milena Rita Almeida",
                            PhoneNumber = "998212236"
                        },
                        new
                        {
                            Id = new Guid("b8cbd154-d9b6-4a51-b84b-c509a7a92ae5"),
                            DDD = (byte)21,
                            Email = "bianca_assis@4now.com.br",
                            Name = "Bianca Liz Assis",
                            PhoneNumber = "992804701"
                        },
                        new
                        {
                            Id = new Guid("df8671a4-e875-40c2-ba3b-c7284d8c6665"),
                            DDD = (byte)32,
                            Email = "alessandra75@jovempanfmtaubate.com.br",
                            Name = "Alessandra Gabrielly Esther Costa",
                            PhoneNumber = "985537746"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
