// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosTech.TechChallenge.Contacts.Command.Infra.Context;

#nullable disable

namespace PosTech.TechChallenge.Contacts.Command.Infra.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20241031222957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosTech.TechChallenge.Contacts.Command.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DDD")
                        .HasMaxLength(2)
                        .HasColumnType("TINYINT")
                        .HasColumnName("DDD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR(9)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef87bd6e-5fc6-4710-ab4a-6b529916a291"),
                            DDD = (byte)43,
                            Email = "pedro-ferreira85@yahoo.com.br",
                            Name = "Pedro Henrique Erick Ferreira",
                            PhoneNumber = "989340101"
                        },
                        new
                        {
                            Id = new Guid("2ef6db3c-671a-4a49-b5ed-a58e44fe7511"),
                            DDD = (byte)63,
                            Email = "thomas.pires@credendio.com.br",
                            Name = "Thomas Vinicius João Pires",
                            PhoneNumber = "989769978"
                        },
                        new
                        {
                            Id = new Guid("1e4150f0-2189-4afb-86bd-4b96a83c759b"),
                            DDD = (byte)11,
                            Email = "julia92@casabellavidros.com.br",
                            Name = "Julia Milena Rita Almeida",
                            PhoneNumber = "998212236"
                        },
                        new
                        {
                            Id = new Guid("a0621708-2cca-4203-be58-91923e370cfc"),
                            DDD = (byte)21,
                            Email = "bianca_assis@4now.com.br",
                            Name = "Bianca Liz Assis",
                            PhoneNumber = "992804701"
                        },
                        new
                        {
                            Id = new Guid("a73fc96a-4414-455e-9679-a4f2d203d70f"),
                            DDD = (byte)32,
                            Email = "alessandra75@jovempanfmtaubate.com.br",
                            Name = "Alessandra Gabrielly Esther Costa",
                            PhoneNumber = "985537746"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
