// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosTech.TechChallenge.Contacts.Command.Infra.Context;

#nullable disable

namespace PosTech.TechChallenge.Contacts.Command.Infra.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    partial class ContactDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosTech.TechChallenge.Contacts.Command.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DDD")
                        .HasMaxLength(2)
                        .HasColumnType("TINYINT")
                        .HasColumnName("DDD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR(9)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99b55381-6ea7-47f0-aa43-d3714ed45d94"),
                            DDD = (byte)43,
                            Email = "pedro-ferreira85@yahoo.com.br",
                            Name = "Pedro Henrique Erick Ferreira",
                            PhoneNumber = "989340101"
                        },
                        new
                        {
                            Id = new Guid("300f2684-c588-41bc-9f80-30a74fa49eb7"),
                            DDD = (byte)63,
                            Email = "thomas.pires@credendio.com.br",
                            Name = "Thomas Vinicius João Pires",
                            PhoneNumber = "989769978"
                        },
                        new
                        {
                            Id = new Guid("5a462400-cabf-46a5-8d68-10dad95b36a4"),
                            DDD = (byte)11,
                            Email = "julia92@casabellavidros.com.br",
                            Name = "Julia Milena Rita Almeida",
                            PhoneNumber = "998212236"
                        },
                        new
                        {
                            Id = new Guid("d7c268cb-bef0-4ea6-9aee-4b1ea4932e54"),
                            DDD = (byte)21,
                            Email = "bianca_assis@4now.com.br",
                            Name = "Bianca Liz Assis",
                            PhoneNumber = "992804701"
                        },
                        new
                        {
                            Id = new Guid("e0b97d74-8d99-4a54-8f75-774f69b35af2"),
                            DDD = (byte)32,
                            Email = "alessandra75@jovempanfmtaubate.com.br",
                            Name = "Alessandra Gabrielly Esther Costa",
                            PhoneNumber = "985537746"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
