apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-contacts-query-api-service
spec:
  type: NodePort
  selector:
    app: tech-challenge-contacts-query-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30007
