apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: tech-challenge-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30005
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30004
  type: NodePort
