// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosTech.TechChallenge.Contacts.Query.Infra.Context;

#nullable disable

namespace PosTech.TechChallenge.Contacts.Query.Infra.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    partial class ContactDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosTech.TechChallenge.Contacts.Query.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DDD")
                        .HasMaxLength(2)
                        .HasColumnType("TINYINT")
                        .HasColumnName("DDD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR(9)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e439b2d-e0fa-4573-8fca-4089a0104cba"),
                            DDD = (byte)43,
                            Email = "pedro-ferreira85@yahoo.com.br",
                            Name = "Pedro Henrique Erick Ferreira",
                            PhoneNumber = "989340101"
                        },
                        new
                        {
                            Id = new Guid("fe0e0f27-01bf-42ae-bf2f-331865319e51"),
                            DDD = (byte)63,
                            Email = "thomas.pires@credendio.com.br",
                            Name = "Thomas Vinicius João Pires",
                            PhoneNumber = "989769978"
                        },
                        new
                        {
                            Id = new Guid("cc63740c-e14f-4bb7-82c5-20a3a81841f0"),
                            DDD = (byte)11,
                            Email = "julia92@casabellavidros.com.br",
                            Name = "Julia Milena Rita Almeida",
                            PhoneNumber = "998212236"
                        },
                        new
                        {
                            Id = new Guid("9f20302a-5200-4cab-9a32-474d09a4c4d9"),
                            DDD = (byte)21,
                            Email = "bianca_assis@4now.com.br",
                            Name = "Bianca Liz Assis",
                            PhoneNumber = "992804701"
                        },
                        new
                        {
                            Id = new Guid("cf4e5592-6973-4c73-a90b-762a33a823ad"),
                            DDD = (byte)32,
                            Email = "alessandra75@jovempanfmtaubate.com.br",
                            Name = "Alessandra Gabrielly Esther Costa",
                            PhoneNumber = "985537746"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
