apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-users-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-users-api
  template:
    metadata:
      labels:
        app: tech-challenge-users-api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup sqlserver.tech-challenge.svc.cluster.local; do echo waiting for sqlserver; sleep 2; done;",
            ]
      containers:
        - name: api
          image: techchallengegrupo3acr.azurecr.io/techchallengegrupo3:221
          ports:
            - containerPort: 8080
      restartPolicy: Always
