apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-users-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-users-db
  template:
    metadata:
      labels:
        app: tech-challenge-users-db
    spec:
      volumes:
        - name: tech-challenge-users-volume
          persistentVolumeClaim:
            claimName: tech-challenge-users-db-pvc
      initContainers:
        - name: tech-challenge-users-init-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          command:
            - /bin/bash
            - -c
            - |
              /opt/mssql/bin/sqlservr --accept-eula & sleep 30
              /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "S3cur3P@ssW0rd" -d master -Q "IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'TechChallengeUsers') CREATE DATABASE [TechChallengeUsers];" -C
          env:
            - name: SA_PASSWORD
              value: "S3cur3P@ssW0rd"
          volumeMounts:
            - name: tech-challenge-users-volume
              mountPath: /var/opt/mssql
      containers:
        - name: tech-challenge-users-sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "S3cur3P@ssW0rd"
            - name: MSSQL_PID
              value: "Developer"
          volumeMounts:
            - name: tech-challenge-users-volume
              mountPath: /var/opt/mssql
      restartPolicy: Always
