apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJ0ZWNoY2hhbGxlbmdlZ3J1cG8zYWNyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJUZWNoQ2hhbGxlbmdlR3J1cG8zQUNSIiwicGFzc3dvcmQiOiJOcWZLMmI3dk1PWjZLVmhnMU5QN09hb0V2dDlEaVFsblFNcEgrVTZWeEgrQUNSQk9CNW0rIiwiZW1haWwiOiJybTM1MzY1OEBmaWFwLmNvbS5iciIsImF1dGgiOiJWR1ZqYUVOb1lXeHNaVzVuWlVkeWRYQnZNMEZEVWpwT2NXWkxNbUkzZGsxUFdqWkxWbWhuTVU1UU4wOWhiMFYyZERsRWFWRnNibEZOY0VnclZUWldlRWdyUVVOU1FrOUNOVzByIn19fQ==
