apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-users-api-service
spec:
  type: NodePort
  selector:
    app: tech-challenge-users-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
