apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-contacts-command-api-service
spec:
  type: NodePort
  selector:
    app: tech-challenge-contacts-command-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30003
